"""Visitor conversations and the source citations attached to each answer."""

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Float,
    ForeignKey,
    Index,
    Integer,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
    Uuid,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base, TimestampMixin
from app.models.enums import MessageRole
from app.models.column_types import enum_type

if TYPE_CHECKING:
    from app.models.document import DocumentChunk


class ChatSession(TimestampMixin, Base):
    __tablename__ = "chat_sessions"

    # A random UUID (not a counter) so session URLs cannot be guessed or enumerated.
    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    # Anonymous id generated by the browser; groups one visitor's sessions. Not a login.
    visitor_id: Mapped[str | None] = mapped_column(String(64), index=True)
    title: Mapped[str | None] = mapped_column(String(255))

    messages: Mapped[list["ChatMessage"]] = relationship(
        back_populates="session",
        cascade="all, delete-orphan",
        passive_deletes=True,
        order_by="ChatMessage.id",
    )


class ChatMessage(TimestampMixin, Base):
    __tablename__ = "chat_messages"
    __table_args__ = (
        CheckConstraint("feedback IS NULL OR feedback IN (-1, 1)", name="feedback_values"),
        Index("ix_chat_messages_session_id_created_at", "session_id", "created_at"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    session_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("chat_sessions.id", ondelete="CASCADE"))
    role: Mapped[MessageRole] = mapped_column(enum_type(MessageRole, "message_role"))
    content: Mapped[str] = mapped_column(Text)
    model: Mapped[str | None] = mapped_column(String(100))  # LLM that wrote an assistant reply
    prompt_tokens: Mapped[int | None] = mapped_column(Integer)
    completion_tokens: Mapped[int | None] = mapped_column(Integer)
    latency_ms: Mapped[int | None] = mapped_column(Integer)
    # False when the assistant declined because no source supported an answer.
    is_grounded: Mapped[bool | None] = mapped_column(Boolean)
    feedback: Mapped[int | None] = mapped_column(SmallInteger)  # 1 = helpful, -1 = not helpful

    session: Mapped[ChatSession] = relationship(back_populates="messages")
    citations: Mapped[list["MessageCitation"]] = relationship(
        back_populates="message",
        cascade="all, delete-orphan",
        passive_deletes=True,
        order_by="MessageCitation.marker",
    )


class MessageCitation(TimestampMixin, Base):
    """One numbered source marker ([1], [2], ...) in an assistant answer."""

    __tablename__ = "message_citations"
    __table_args__ = (
        UniqueConstraint("message_id", "marker", name="uq_message_citations_message_id_marker"),
        CheckConstraint("marker >= 1", name="marker_positive"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    message_id: Mapped[int] = mapped_column(ForeignKey("chat_messages.id", ondelete="CASCADE"))
    # SET NULL, not CASCADE: re-indexing a document replaces its chunks, but an old
    # answer must keep showing what it cited. The title and snippet below are snapshots.
    chunk_id: Mapped[int | None] = mapped_column(
        ForeignKey("document_chunks.id", ondelete="SET NULL"), index=True
    )
    marker: Mapped[int] = mapped_column(SmallInteger)
    source_title: Mapped[str] = mapped_column(String(255))
    page_number: Mapped[int | None] = mapped_column(Integer)
    snippet: Mapped[str] = mapped_column(Text)
    score: Mapped[float | None] = mapped_column(Float)

    message: Mapped[ChatMessage] = relationship(back_populates="citations")
    chunk: Mapped["DocumentChunk | None"] = relationship(back_populates="citations")
